version: '3.4'

services:
  myusermicroservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
  user.api:
    image: myusermicroservice/user.api
    environment:
      - ConnectionString=Data Source=JUANFDOCASTRO\SQLEXPRESS;Initial Catalog=MYUSER;Persist Security Info=True;User ID=UserPrueba;Password=passw0rd
    expose:
      - "80"
    ports:
      - "1433:80"